### ISSUE TITLE
issue in Driver Mutation module with staging api

### ISSUE THREAD

**Issue by heimannch** [CRI-iAtlas/iatlasGraphQLClient#14]
When I click on any point at the volcano plot, the following message appears:
<img width="637" alt="image" src="https://github.com/CRI-iAtlas/iatlasGraphQLClient/assets/32350126/b0b36dc4-2398-4b1d-ad17-efb4b9e25036">
Since there's no "calculate" button in this module, I checked the error message that is generated:
```
Warning: Problem while computing `status = forcats::fct_relevel(.data$status, "Wt", "Mut")`.
ℹ Unknown levels in `f`: Wt, Mut
```

**Comment by andrewelamb** [comment]
the "driver_mutation" type accidentally got renamed "driver mutation" in the new database, fixing now
