### ISSUE TITLE
CNV module with limited data from staging API

### ISSUE THREAD

**Issue by heimannch** [CRI-iAtlas/iatlasGraphQLClient#15]
In the default settings of the CNV module, the production API returns: `Total number of rows: 7, Number of genes: 2,` but the staging returns only `Total number of rows: 7, Number of genes: 2`

**Comment by andrewelamb** [comment]
@heimannch Those look exactly the same?

**Comment by heimannch** [comment]
The plots and tables are different between staging and production:

- staging:
<img width="382" alt="image" src="https://github.com/CRI-iAtlas/iatlasGraphQLClient/assets/32350126/a700e1f3-103b-4c84-a854-3c3ea4a87642">

- production:
<img width="382" alt="image" src="https://github.com/CRI-iAtlas/iatlasGraphQLClient/assets/32350126/2da3b245-eb90-4819-9f4f-096c8324236e">

**Comment by andrewelamb** [comment]
I"ve figured out the issue, not all the results got migrated to the new database, this will be fixed with the rebuild

**Comment by heimannch** [comment]
@andrewelamb, it was brought to my attention that the version of the app before the database (shiny-iatlas) has way more results for the CNV module.
<img width="474" alt="image" src="https://github.com/CRI-iAtlas/iatlasGraphQLClient/assets/32350126/1e4022cc-cba1-4d2d-91c6-845de5277a8d">
 @Gibbsdavidl has mentioned that he can retrieve all the results from the API call, but they are not making it into the table in the module.

**Comment by heimannch** [comment]
Ok, I found the offending code, it's actually in `iatlas-app` code.

In https://github.com/CRI-iAtlas/iatlas-app/blob/staging/R/copy_number_response_server.R, line 51, the query to get the gene list is:
```
 iatlasGraphQLClient::query_genes(entrez = 1:100)
```
Which causes the app to only show the genes with entrez ids between 1 and 100. I tried to remove this argument, but then the app crashes, which might explain why this was included in the first place. After some experimentation, I concluded that the query works with no issues for the range of 1:10000:

```
 iatlasGraphQLClient::query_genes(entrez = 1:10000)
```

I will include this change in the upcoming release of iAtlas, but it doesn't look like a good long term solution. @andrewelamb, do you think there is anything we could do to be able to retrieve all gene ids available in the CNV module?

For the record, I also tried to replace ` iatlasGraphQLClient::query_genes(entrez = 1:100)` with `iatlasGraphQLClient::query_copy_number_result_genes()`, and also got ` Error in : Bad Gateway (HTTP 502)`
I also tested with the staging API and got the same issues.
