### ISSUE TITLE
extracellular network function `iatlasGraphQLClient::query_nodes()` not working

### ISSUE THREAD

**Issue by heimannch** [CRI-iAtlas/iatlasGraphQLClient#16]
```
> x <- iatlasGraphQLClient::query_nodes()
Error in create_result_from_cursor_paginated_api_query(query_args = query_args,  : 
  object 'query_file' not found
```

**Comment by andrewelamb** [comment]
@heimannch Do you know where in the code this is happening?

**Comment by heimannch** [comment]
Do you mean the app code or the api code? In the app, this function is being called in `extracellular_network_main_server.R -> extracellular_networks_functions.R`

**Comment by andrewelamb** [comment]
I mean where is `iatlasGraphQLClient::query_nodes()` being called without any arguments. It's not meant to be.

**Comment by heimannch** [comment]
Ah, nowhere in the code. I just did that because I thought it would be helpful in debugging - the issue is that no network is displayed in the Extracellular Network module.

**Comment by andrewelamb** [comment]
I can't run the app locally so I can't diagnose something like this. If there's an error, or a iatlasGraphQLClient function that returning the wrong information, then I could help.

**Comment by heimannch** [comment]
When I run the app, the issue when running the extracellular network module is `Error in : Gateway Timeout (HTTP 504)`.

I get this error when I select genesets (Immunomodulators and Extracellular Network Genes), but if I select few genes everything works fine. I’m assuming this issue is due to settings of the staging API, or the geneset information.
