### ISSUE TITLE
query_gene_nanostring_expression() doesn't return results for Chen_CanDisc_2016 dataset

### ISSUE THREAD

**Issue by heimannch** [CRI-iAtlas/iatlasGraphQLClient#6]
The function ` iatlasGraphQLClient::query_gene_nanostring_expression()` does not return results for samples from the Chen dataset.

Below some examples of queries I attempted:

```
x <- iatlasGraphQLClient::query_gene_nanostring_expression(entrez = 1493) #no entry for Chen_CanDisc_2016

x <- iatlasGraphQLClient::query_gene_nanostring_expression(samples = "Chen_CanDisc_2016-p18-p18_pre") 
```

**Comment by andrewelamb** [comment]
@heimannch It doesn't look like that particular sample isn't in the database at all:

`
nrow(query_samples(samples = "Chen_CanDisc_2016-p18-p18_pre"))
[1] 0
`
If it's not in as a sample it won't be in other tables.

**Comment by heimannch** [comment]
I see. Yeah, indeed there is a mismatch in the samples names for this dataset. I updated the file in Synapse, hopefully it will solve this issue. Thanks for the clarification!
