### ISSUE TITLE
ICI data tagged as TCGA

### ISSUE THREAD

**Issue by Gibbsdavidl** [CRI-iAtlas/iatlasGraphQLClient#7]
library(iatlasGraphQLClient)
dataset_tags <- iatlasGraphQLClient::query_dataset_tags()
dataset_tags[dataset_tags$tag_name == 'TCGA_Study',]

Table returned includes:
"TCGA_Study"	"TCGA Study"	"TCGA Study"	NA	NA	"Chen 2016 - SKCM, Anti-CTLA4"	"Chen_CanDisc_2016"
"TCGA_Study"	"TCGA Study"	"TCGA Study"	NA	NA	"Choueiri 2016 - KIRC, PD-1"	"Choueiri_CCR_2016"
"TCGA_Study"	"TCGA Study"	"TCGA Study"	NA	NA	"Gide 2019 - SKCM, PD-1 +/- CTLA4"	"Gide_Cell_2019"

In the 6th column, those are ICI data sets, not part of TCGA.

**Comment by heimannch** [comment]
This query returns which datasets have annotation for TCGA_Study.
What I understand you want to get can be achieved with:
```
tcga_studies <- iatlasGraphQLClient::query_tags_with_parent_tags(parent_tags = "TCGA_Study")
tcga_studies$tag_name
```

**Comment by Gibbsdavidl** [comment]
Oh, my issue was that ICI data sets were tagged with "TCGA_Study" as above.  
For example, the "Choueiri 2016 - KIRC, PD-1" data is not from TCGA, yeah?

**Comment by andrewelamb** [comment]
I think that means that those ICI patients have been labeled using the 33 "TCGA_Study" cancer types.

**Comment by Gibbsdavidl** [comment]
OK, thanks!
