### ISSUE TITLE
Add neoantigens

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlasGraphQLClient#8]
AC:

- Add table to database called neoantigens with columns 
  - patient_id (foreign_key)
  - feature_id (foreign_key)
  - gene_id (foreign_key)
  - tpm

   
- Add query to api that 
  - returns data with attributes
    - patient_name
    - feature_name
    - entrez
    - tpm
  - is filterable by 
    - patient
    - feature
    - gene
  
- Add query to client

In production by 02/24/23

**Comment by andrewelamb** [comment]
@heimannch could you check the above?

@milen-sage Should we add this to the next sprint?

**Comment by heimannch** [comment]
@andrewelamb looks good!
